filter:
  excluded_paths:
    - vendor/

build:
  environment:
    php:
      version: 7.4
      pecl_extensions:
        - ds
      ini:
        "date.timezone": "UTC"
        "opcache.enable_cli": 1
        "opcache.enable": 1
        "extension": "ds.so"
  dependencies:
    override:
      - composer install --prefer-dist --classmap-authoritative
  nodes:
    analysis:
      tests:
        override:
          - command: vendor/bin/phpunit --coverage-clover=build/coverage/clover.xml
            coverage:
              file: build/coverage/clover.xml
              format: php-clover
          - command: php-scrutinizer-run

checks:
  php: true
