DROP TABLE IF EXISTS `user`;
CREATE TABLE `users` (
  `id` bigint(32) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `username` varchar(255) NOT NULL,
  `dateUtc` datetime NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `avatar_filename` varchar(255) DEFAULT NULL,
  `background_filename` varchar(255) DEFAULT NULL,
  `twitter_username` varchar(255) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `bio` varchar(255) DEFAULT NULL,
  `timezone` varchar(255) NOT NULL,
  `language` varchar(255) DEFAULT NULL,
  `status` int() NOT NULL,
  `is_dark_mode` tinyint(1) NOT NULL DEFAULT '0',
  `image_count` bigint(32) NOT NULL DEFAULT '0',
  `album_count` bigint(32) NOT NULL DEFAULT '0',
  `likes` bigint(32) NOT NULL DEFAULT '0' COMMENT 'Likes made to content owned by this user',
  `liked` bigint(32) NOT NULL DEFAULT '0' COMMENT 'Likes made by this user',
  `following` bigint(32) NOT NULL DEFAULT '0',
  `followers` bigint(32) NOT NULL DEFAULT '0',
  `content_views` bigint(32) NOT NULL DEFAULT '0',
  `notifications_unread` bigint(32) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`) USING BTREE,
  UNIQUE KEY `email` (`email`) USING BTREE,
  KEY `date_gmt` (`date_gmt`),
  KEY `status` (`status`),
  KEY `is_admin` (`is_admin`),
  KEY `is_manager` (`is_manager`),
  KEY `is_private` (`is_private`),
  KEY `is_dark_mode` (`is_dark_mode`),
  KEY `newsletter_subscribe` (`newsletter_subscribe`),
  KEY `show_nsfw_listings` (`show_nsfw_listings`),
  KEY `image_count` (`image_count`),
  KEY `album_count` (`album_count`),
  KEY `image_keep_exif` (`image_keep_exif`),
  KEY `image_expiration` (`image_expiration`),
  KEY `registration_ip` (`registration_ip`),
  KEY `likes` (`likes`),
  KEY `following` (`following`),
  KEY `followers` (`followers`),
  KEY `liked` (`liked`),
  KEY `content_views` (`content_views`),
  FULLTEXT KEY `searchindex` (`name`,`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;