name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dependencies
        run: sudo apt-get update && sudo apt-get install -y imagemagick ffmpeg

      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: imagick, opcache, mbstring, ds
          ini-values: opcache.enable_cli = 1, opcache.enable = 1, pcov.directory=src
          coverage: pcov

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --classmap-authoritative --ignore-platform-reqs

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Run tests with phpunit
        run: vendor/bin/phpunit --coverage-clover=build/coverage/clover.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: build/coverage/clover.xml
          fail_ci_if_error: false
